name: Publish Documentation

on:
  release:
    types: [published, created, edited]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ###############################################################
      # Checkout main repo
      ###############################################################
      - name: Check out main repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      ###############################################################
      # Lookup the previous tag
      ###############################################################
      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      ###############################################################
      # Checkout repo from previous tag
      ###############################################################
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.previoustag.outputs.tag }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          cache: 'maven'
          server-id: jd-oss-github # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          settings-path: ${{ github.workspace }} # location for the settings.xml file
        env:
          MAVEN_USERNAME: ${{ secrets.JD_OSS_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.JD_OSS_MAVEN_PASSWORD }}
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      ###############################################################
      # Generate JavaDocs via maven
      ###############################################################
      - name: Generate JavaDocs
        run: mvn -B javadoc:javadoc --file pom.xml -s ${{ github.workspace }}/settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.JD_OSS_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.JD_OSS_MAVEN_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ###############################################################
      # Publish generated JavaDocs to Github Pages
      ###############################################################
      - name: Publish JavaDocs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:  ./target/site/apidocs
